/*************** AUTO GENERATED BY REMOTE CONTROL MODULE ***************/

var config
= {
  address: "0.0.0.0",
  ipWhitelist: [
    "192.168.1.0/24",
    "127.0.0.1",
    "::ffff:127.0.0.1",
    "::1"
  ],
  timeFormat: 12,
  zoom: 0.5,
  modules: [
    {
      module: "MMM-Remote-Control",
      config: {
        showModuleApiMenu: true,
        secureEndpoints: true,
        apiKey: "test123"
      }
    },
    {
      module: "WallberryTheme",
      position: "fullscreen_below",
      animateIn: "fadeIn",
      animateOut: "fadeOut",
      config: {
        backgroundOpacity: 0.5,
        unsplashAccessKey: "C0Uw7Qrq1uvf_9Wug2buL4mCYC6AvD6qWvjqaZWkVxg",
        collections: "9822150"
      }
    },
    {
      module: "alert",
      config: {}
    },
    {
      module: "updatenotification",
      animateIn: "fadeInDown",
      position: "top_bar",
      config: {}
    },
    {
      module: "WallberryTheme/WB-clock",
      animateIn: "faceIn",
      position: "top_left",
      config: {
        localCityName: "Cebu City"
      }
    },
    {
      module: "calendar",
      header: "Your Events",
      position: "top_left",
      animateIn: "slideInLeft",
      animateOut: "slideOutLeft",
      updateOnFetch: "false",
      config: {
        calendars: [
          {
            fetchInterval: 680000,
            symbol: "calendar-check",
            url: "https://ics.calendarlabs.com/63/a9fe3549/Philippines_Holidays.ics"
          },
          {
            fetchInterval: 20000,
            symbol: "star",
            url: "https://calendar.google.com/calendar/ical/king0fskiez11%40gmail.com/private-a71c8ac945f910e56e98401608c04e99/basic.ics"

          }
        ]
      }
    },
    {
      module: "newsfeed",
      position: "lower_third",
      config: {
        feeds: [
          {
            title: "Philstar Headlines",
            url: "http://www.inquirer.net/fullfeed"
          }
        ]
      }
    },
    {
      module: "WallberryTheme/WB-weather",
      position: "bottom_bar",
      config: {
        providerName: "pirateweather",
        weatherEndpoint: "forecast",
        apiKey: "M4fgPStHEEABTG85h27kecHfvx3fmaMJ",
        lat: 10,
        lon: 123
      }
    },
    {
      module: "MMM-OnSpotify",
      position: "top_right",
      config: {
        clientID: "62b60370dfb8457b87302f92338921d7",
        clientSecret: "3af835446e024f90aee9492e9f47f6b2",
        accessToken: "BQBdXG6YLqD9lBU252uRMjGHYT1IFEO_y07_x68dHvQWjJ1DHS2deZgEfYOoLb8gPkdd1ZKk4WGuTVmC0tKGwNZdDEmOkv6GYEF3pcgsWCkNZLio8vX_LbSV7QedJ1Awm96CQxrtzeLT1yykuZcmn3bEBpIXpCs05eD-H7k9L0DrvK7338edaHGWrwaZlOQHMs_TMn3FW-5Q-ZesNEyW87SD005Zjw",
        refreshToken: "AQDcXUfvUwB5cAWjr56QZV8fuDARH1gBAB3oTFX3uQMWxrT9J-kzszHz7eg2wsb1QKKQ7Hd561oXCoQOXh18ccSkackHws7nVZW6gIMGDISdHpjiMRNuUxLmn6C51Y9OtDg",
        displayWhenEmpty: "none",
        isPlayingHidden: 2,
        isEmptyHidden: 4,
        fadeAnimations: true,
        transitionAnimations: true,
        blurCorrectionInFrameSide: true
      }
    },
    {
      module: "MMM-QRCode",
      position: "left",
      header: "Connect to Companion",
      config: {
        apiKey: "test123",
        text: "HELLO WORLD!",
        useQRconnection: true,
        showRaw: false,
        imageSize: 150,
        colorDark: "#fff",
        colorLight: "#000"
      }
    },
  ],
  useHttps: false,
  httpsPrivateKey: "",
  httpsCertificate: "",
  locale: "en-US"
};

/*************** DO NOT EDIT THE LINE BELOW ***************/
if (typeof module !== "undefined") { module.exports = config; }
